### ISSUE TITLE
Add provider to Community Providers list

### ISSUE THREAD

**Issue by kristofferahl** [kristofferahl/terraform-provider-healthchecksio#11]
https://www.terraform.io/docs/providers/type/community-index.html

**Comment by abeluck** [comment]
This would be really great, especially with TF13 now available.

**Comment by kristofferahl** [comment]
**The provider is now published to the [terraform registry](https://registry.terraform.io/providers/kristofferahl/healthchecksio/latest)!**

As of version v1.6.3, the release pipeline has been setup to create valid provider releases on github.
Going forward you may now use the following syntax to install the provider.

```hcl
terraform {
  required_providers {
    healthchecksio = {
      source = "kristofferahl/healthchecksio"
      version = "1.6.3"
    }
  }
}

provider "healthchecksio" {
  # Configuration options
}
```
