### ISSUE TITLE
Support desc field when creating a check url

### ISSUE THREAD

**Issue by avadhutp** [kristofferahl/terraform-provider-healthchecksio#19]

**Comment by icaho** [comment]
https://github.com/kristofferahl/terraform-provider-healthchecksio/pull/20 - relies on - https://github.com/kristofferahl/go-healthchecksio/pull/4

**Comment by kristofferahl** [comment]
@avadhutp @icaho Merged the PR and added to docs, examples and tests.
Version 1.6.0 is now released and it contains your PR. Thanks for helping out!
https://github.com/kristofferahl/terraform-provider-healthchecksio/releases/tag/v1.6.0
