### ISSUE TITLE
[request] support self hosted variant

### ISSUE THREAD

**Issue by mullholland** [kristofferahl/terraform-provider-healthchecksio#23]
Hi,
would it be possible to support the self hosted variant of [healthcheck.io](https://healthchecks.io/docs/self_hosted/)?
I would love to manage resources in my own instance with terraform.

**Comment by kristofferahl** [comment]
To be honest, I think it would be quite a lot of work and perhaps not the best fit for this provider. If we’re talking self hosting it on AWS or similar a module using existing cloud providers should be totally possible. But again, a bit outside the scope of this provider. If you are a Kubernetes user, an operator might be a good fit. I started working on one (https://github.com/kristofferahl/healthchecksio-operator) but it’s no where near finished and no near future plans for it. Let me know what you are thinking.

**Comment by kristofferahl** [comment]
@yteraoka has provided a fix for allowing this provider to be used against self hosted Healthchecks.io. Was this all you needed @mullholland or should we leave this issue open?
