### ISSUE TITLE
Mac M1 support

### ISSUE THREAD

**Issue by acraftydev** [kristofferahl/terraform-provider-healthchecksio#25]
hi

Would like to start using this provider, I have recently started using a new Mac with the arm M1 chip and would need a Darwin_arm64 build. Go 1.16 supports this and the new releases of goreleaser supports generating that build (https://github.com/goreleaser/goreleaser/releases/tag/v0.156.2). I'm happy to try and create a PR, looks like the main changes would be in GitHub Actions and dockerfile.test, assuming not much change to actual code.

thanks
Andrew

**Comment by kristofferahl** [comment]
Awesome! PR welcome and I see you already created one. 😀
