### ISSUE TITLE
[question] creating pagerduty integration with pagerduty provider

### ISSUE THREAD

**Issue by danielpof** [kristofferahl/terraform-provider-healthchecksio#27]
Hi, we provision our PagerDuty trough terraform using the [PagerDuty provider](https://registry.terraform.io/providers/PagerDuty/pagerduty/latest/docs), in it we're able to create the healthcheck.io integration.

That said there doesn't seem to be any way on the provider or even healthcheck.io to associate the PagerDuty integration with a new created check.

Is there really no way to do this fully automatically?

**Comment by kristofferahl** [comment]
Hi, I might be missing the point but are you perhaps looking for data.healthchecksio_channel?

```terraform
resource "healthchecksio_check" "test" {
  name = "test-check"
  desc = "A test check"

  tags = [
    "go",
    "gophers",
    "unite",
  ]

  grace    = 120 # seconds
  schedule = "0,30 2 * * *"
  timezone = "Asia/Tokyo"

  channels = [
    data.healthchecksio_channel.pagerduty.id,
  ]
}

data "healthchecksio_channel" "pagerduty" {
  kind = "pd"
}
```

**Comment by danielpof** [comment]
Yes i saw healthcheckio_channel, but it seems to only be a data source, so I can only reference integrations that were already created by hand.

What I want is to create the integration from terraform using healthcheckio and pagerduty providers. On the pagerduty side I can create a service with the healthcheck.io intgration using `pagerduty_service` however now I don't see a way to use the integration key output as an input to create the appropriate channel on healthcheck.io provider. I looked at the API reference and this seems to be an API limitation, I just wanted to confirm before trying to reach out to heathcheck.io.

But now I have no way to create the channel with that integration key on healthcheck.io.

**Comment by kristofferahl** [comment]
Sorry, I misunderstood. I thought you wanted to connect an existing healthchecks.io integration to a check.
I believe you are correct, it is an api limitation. We cannot add a healthchecksio_channel resource as this is not supported by the healthchecks.io API.

I'm closing this issue for now as there is nothing we can do about it. Please feel free to open an issue if they end up adding support in their api.
