### ISSUE TITLE
More than one channel of the same kind.

### ISSUE THREAD

**Issue by fhziliotti** [kristofferahl/terraform-provider-healthchecksio#30]
We have more than one Slack integration, and currently terraform does not recognize both channels
data "healthchecksio_channel" "slack_production" {
   kind = "slack"
}

data "healthchecksio_channel" "slack_internal" {
   kind = "slack"
}

Is there any way we can use it?

**Comment by kristofferahl** [comment]
Hi!
There is a "name" property you can use to filter the data source.

```terraform
data "healthchecksio_channel" "slack-prod" {
  kind = "slack"
  name = "prod-slack-integration"
}

data "healthchecksio_channel" "slack-dev" {
  kind = "slack"
  name = "dev-slack-integration"
}
```

It should work but let me know if it doesn't! It does require the integration to have unique names.

**Comment by kristofferahl** [comment]
I will leave this open until you can confirm the above works @fhziliotti

**Comment by fhziliotti** [comment]
It didn't work the way above. Do you have any guidance for us to make it work or force the ID to be a specific one?

**Comment by kristofferahl** [comment]
To be honest, I can't see any reason for that to not work. And you are specifying both name and kind?
Can you post the 2 data resources that isn't working for you?

**Comment by fhziliotti** [comment]
It worked, putting it that way with the name attribute

```yaml
data "healthchecksio_channel" "slack_production" {
  kind = "slack"
  name = "Slack XXXXX"
}

data "healthchecksio_channel" "slack_internal" {
  kind = "slack"
  name = "Slack YYYY"
}
```
