### ISSUE TITLE
Fail to remove check's channel in terraform

### ISSUE THREAD

**Issue by ThomasKwan-shopline** [kristofferahl/terraform-provider-healthchecksio#34]
Hi I have create a check by terraform by following script:

```
resource "healthchecksio_check" "testing-1" {
	name = "testing 1"
	channels = [ <channel_uuid> ]
	tags = [ "tag_1" ]
	grace = 3600
	schedule = "30 1 * * *"
	timezone = "Asia/Hong_Kong"
	desc = "message here"
}
```

after apply it can success to create a new check
<img width="1318" alt="Screenshot 2024-02-23 at 12 01 30 PM" src="https://github.com/kristofferahl/terraform-provider-healthchecksio/assets/148204512/4976895b-786c-4d11-b889-cb4d5e0990f1">

Then I want to remove this channel by following script:

```
resource "healthchecksio_check" "testing-1" {
	name = "testing 1"
	tags = [ "tag_1" ]
	grace = 3600
	schedule = "30 1 * * *"
	timezone = "Asia/Hong_Kong"
	desc = "message here"
}

```

and the plan and apply result is below
```
Terraform will perform the following actions:

  # healthchecksio_check.testing-1 will be updated in-place
  ~ resource "healthchecksio_check" "testing-1" {
      ~ channels  = [
          - "<channel_uuid>",
        ]
        id        = "<check_uuid>"
        name      = "testing 1"
        tags      = [
            "tag_1",
        ]
        # (7 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

after apply it, I expect it can remove the channel, but it cannot. Can I know how to resolve this issue?

**Comment by kristofferahl** [comment]
@ThomasKwan-shopline Thanks for reporting the issue. I just confirmed, this is a bug! I will see if I can find the issue and get back to you.

**Comment by kristofferahl** [comment]
@ThomasKwan-shopline Found the bug, updated the underlying client (where the issue was). New version of provider will be released (v.2.0.0) as this fix could break existing resources.

**Comment by kristofferahl** [comment]
@ThomasKwan-shopline Here's the new release, should be available in registry in a short while.
https://github.com/kristofferahl/terraform-provider-healthchecksio/releases/tag/v2.0.0
