### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by kristofferahl** [kristofferahl/terraform-provider-healthchecksio#6]
It seems we're missing a license. Does Apache License 2.0 work for you guys?

@masutaka @rossmckelvie

**Comment by rossmckelvie** [comment]
I prefer MIT because it's simple, but Apache 2 accomplishes the same thing with more words. It's your project, whatever you feel most comfortable with works for me.

**Comment by masutaka** [comment]
I second that. I agree you choose the Apache 2 license.

**Comment by kristofferahl** [comment]
I'll add it!
