### ISSUE TITLE
Setup CI release pipeline

### ISSUE THREAD

**Issue by kristofferahl** [kristofferahl/terraform-provider-healthchecksio#9]
Pipeline steps

1. Run unit tests
1. Run integration/smoke tests
1. Create release using gorelaser

**Comment by kristofferahl** [comment]
Any experience with CI for open source projects? Needs to support building and running docker container for testing. Thinking Circle CI or Travis might be a good fit.

@masutaka @rossmckelvie

**Comment by masutaka** [comment]
Yes, I mostly use CircleCI. CircleCI is complex but useful. I think TravisCI is legacy.

I think that it's easy to add `run test` to CI in the beginning.

**Comment by kristofferahl** [comment]
Will have a go at this once PR #12 is done!
